openapi: 3.0.0
info:
  title: "Your Application API document"
  version: "1.0.0"
schemes:
  - http
paths:
  /api/auth/login:
    $ref: "login.yaml"

  /api/auth/logout:
    $ref: "logout.yaml"

  /api/auth/change-password:
    $ref: "changePassword.yaml"

  /api/auth/register:
    $ref: "register.yaml"

  #User
  /api/users/profile:
    get: { $ref: "getMyAccount.yaml#/get" }
    $ref: "updateUserLogin.yaml"

  /api/users/avatar:
    $ref: "updateAvatar.yaml"

  /api/users/{id}:
    $ref: "updateUserById.yaml"
    get: { $ref: "getUserById.yaml#/get" }

  /api/users/{id}/deActive:
    $ref: "blockUserById.yaml"

  /api/users/{id}/active:
    $ref: "activeUserById.yaml"

  #Department

  /api/departments/{id}:
    $ref: "getDepartmentById.yaml"
    put: { $ref: "editDepartmentById.yaml#/put" }

  /api/departments:
    $ref: "getDepartment.yaml"
    post: { $ref: "createDepartment.yaml#/post" }
  #Assets

  /api/users/assets:
    $ref: "createAssets.yaml"

  /api/users/assets/me:
    $ref: "getAssets.yaml"

  /api/users/assets/{id}:
    $ref: "getAssetsById.yaml"
    put: { $ref: "editAssetsById.yaml#/put" }

  #Contact
  /api/users/requests:
    $ref: "createContact.yaml"

  /api/users/requests/{id}:
    $ref: "getContactById.yaml"
    patch: { $ref: "setSttContact.yaml#/patch" }
    put: { $ref: "editContact.yaml#/put" }
    delete: { $ref: "deleteContact.yaml#/delete" }
  /api/users/requests/manager:
    $ref: "getManagerUserContact.yaml"
  /api/users/requests/member/{type}:
    $ref: "getContactStatus.yaml"
  /api/users/requests/all:
    $ref: "getContact.yaml"

  #timeKeep
  /api/users/time-keep/all:
    $ref: "getTimeKeep.yaml"

  /api/users/time-keep/by-day:
    $ref: "getTimeKeep.yaml"

  /api/users/time-keep/work-time:
    $ref: "getTimeKeep.yaml"

  /api/users/time-keep/not-work/{year}/{month}:
    $ref: "getNotWorkTimeKeep.yaml"

  /api/users/time-keep/check-in:
    $ref: "createTimeKeep.yaml"

  /api/users/time-keep/check-out:
    $ref: "updateTimeKeep.yaml"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
