openapi: 3.0.0
info:
  title: "Your Application API document"
  version: "1.0.0"
servers:
  - url: http://localhost:8080/api
paths:
  #auth
  /auth/login:
    $ref: "login.yaml"

  /auth/logout:
    $ref: "logout.yaml"

  /auth/change-password:
    $ref: "changePassword.yaml"

  /auth/register:
    $ref: "register.yaml"
  #department
  /departments/{id}:
    $ref: "getDepartmentById.yaml"
    put:
      $ref: "editDepartmentById.yaml#/put"

  /departments:
    $ref: "getDepartment.yaml"
    post:
      $ref: "createDepartment.yaml#/post"
  #asset
  /users/assets:
    $ref: "createAssets.yaml"

  /users/assets/me:
    $ref: "getAssets.yaml"

  /users/assets/{id}:
    $ref: "getAssetsById.yaml"
    put:
      $ref: "editAssetsById.yaml#/put"
  # requests
  /users/requests:
    $ref: "createContact.yaml"

  /users/requests/{id}:
    $ref: "getContactById.yaml"
    patch:
      $ref: "setSttContact.yaml#/patch"
    put:
      $ref: "editContact.yaml#/put"
    delete:
      $ref: "deleteContact.yaml#/delete"

  /users/requests/manager:
    $ref: "getManagerUserContact.yaml"

  /users/requests/member/{type}:
    $ref: "getContactStatus.yaml"

  /users/requests/all:
    $ref: "getContact.yaml"
  # time keep
  /users/time-keep/all:
    $ref: "getTimeKeep.yaml"

  /users/time-keep/by-day:
    $ref: "getTimeKeep.yaml"

  /users/time-keep/work-time:
    $ref: "getTimeKeep.yaml"

  /users/time-keep/not-work/{year}/{month}:
    $ref: "getNotWorkTimeKeep.yaml"

  /users/time-keep/check-in:
    $ref: "createTimeKeep.yaml"

  /users/time-keep/check-out:
    $ref: "updateTimeKeep.yaml"
  #user
  /users/profile:
    get:
      $ref: "getMyAccount.yaml#/get"
    $ref: "updateUserLogin.yaml"

  /users/avatar:
    $ref: "updateAvatar.yaml"

  /users/{id}:
    $ref: "getUserById.yaml"
    put:
      $ref: "updateUserById.yaml#/put"

  /users/{id}/deActive:
    $ref: "blockUserById.yaml"

  /users/{id}/active:
    $ref: "activeUserById.yaml"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string

  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
