openapi: 3.0.0
info:
  title: "Your Application API document"
  version: "1.0.0"
schemes:
  - http
# chi chap nhan request dang json
# consumes:
#   - application/json
# chi nhan response dang json
# produces:
#   - application/json
paths:
  /api/auth/login:
    $ref: "login.yaml"

  /api/auth/logout:
    $ref: "logout.yaml"

  /api/auth/change-password:
    $ref: "changePassword.yaml"

  /api/auth/register:
    $ref: "register.yaml"

  #User
  /api/users/update/user/{id}:
    $ref: "updateUserById.yaml"

  /api/users/update/my-account:
    $ref: "updateUserLogin.yaml"

  /api/users/get-user/{id}:
    $ref: "getUserById.yaml"

  /api/users/my-account:
    $ref: "getMyAccount.yaml"

  /api/users/delete/users/{id}:
    $ref: "blockUserById.yaml"

  /api/users/active/users/{id}:
    $ref: "activeUserById.yaml"

  /api/users/gets:
    $ref: "getUsers.yaml"

  /api/users/get/department/{department_id}:
    $ref: "getByDepartment.yaml"

  /api/users/search/{search}:
    $ref: "searchUsers.yaml"

  /api/users/update/avatar:
    $ref: "updateAvatar.yaml"

  #Department
  /api/users/department/new:
    $ref: "createDepartment.yaml"

  /api/users/department/edit/{id}:
    $ref: "editDepartmentById.yaml"

  /api/users/department/get/{id}:
    $ref: "getDepartmentById.yaml"

  /api/users/department/get:
    $ref: "getDepartment.yaml"

  #Assets
  /api/users/assets/new:
    $ref: "createAssets.yaml"

  /api/users/assets/edit/{id}:
    $ref: "editAssetsById.yaml"

  /api/users/assets/get/{id}:
    $ref: "getAssetsById.yaml"

  /api/users/assets/get:
    $ref: "getAssets.yaml"

  #Contact
  /api/users/request/new:
    $ref: "createContact.yaml"

  /api/users/request:
    $ref: "getContact.yaml"

  /api/users/request/get/{id}:
    $ref: "getContactById.yaml"

  /api/users/request/update/{id}:
    $ref: "setSttContact.yaml"

  /api/users/request/manager:
    $ref: "getManagerUserContact.yaml"

  /api/users/member/request/{type}:
    $ref: "getContactStatus.yaml"

  /api/users/request/user-create/{id}:
    $ref: "userCreateContact.yaml"

  /api/users/request/delete/{id}:
    $ref: "deleteContact.yaml"

  #timeKeep
  /api/users/time-keep/new:
    $ref: "createTimeKeep.yaml"

  /api/users/time-keep/update:
    $ref: "createTimeKeep.yaml"

  /api/users/time-keep/get:
    $ref: "createTimeKeep.yaml"

  /api/users/time-keep/getByDay:
    $ref: "createTimeKeep.yaml"

  /api/users/time-keep/getWorkTime:
    $ref: "createTimeKeep.yaml"

  /api/users/time-keep/getNotWork/{year}/{month}:
    $ref: "getNotWorkTimeKeep.yaml"

components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string

  responses:
    200:
      $ref: "responses.yaml#/200"
    201:
      $ref: "responses.yaml#/201"
    204:
      $ref: "responses.yaml#/204"
    400:
      $ref: "responses.yaml#/400"
    401:
      $ref: "responses.yaml#/401"
    404:
      $ref: "responses.yaml#/404"
    default:
      $ref: "responses.yaml#/default"
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
