version: '3'

services:
  nginx:
    image: nginx
    container_name: c-nginx
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default_000.conf:/etc/nginx/conf.d/default.conf

  php:
    build:
      context: ./
      dockerfile: Dockerfile
    image: i-php
    container_name: c-php
    volumes:
      - ./:/var/www/html

  mysql:
    image: mysql:8.0.29-oracle
    container_name: c-mysql
    ports:
      - "3307:3306"
    volumes:
      - ./docker/db:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: laravel
      MYSQL_USER: admin
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: 123

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: c-phpmyadmin
    ports:
      - "8081:80"
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      # PMA_USER: root
      # PMA_PASSWORD: 123
      PMA_ARBITRARY: 1